## 
## Gitlab CI for .Net
##
## 作者:黄涛
## 站点:https://github.com/htve/GitlabCIForDotNet

## 构建的阶段与步骤
stages:
  - build
  - test
  - build_unpack
  - upload_file
  - deploy

## 定义变量
before_script:
  ##-----------------------------可变更参数----------------------------------
  ## 文件目录
  - $global:FilePath="C:\\Multi-Runner1"
  ## 覆盖率过滤器
  - $global:CoverFilters="-:Abp*;-:Ninetowns.IDecl.Tests;-:Castle.*"
  ## 部署时执行的控制台程序(必须在web主目录下)
  - $global:Console="Ninetowns.IDecl.Migrator.dll"
  ##-------------------------------------------------------------------------
  - $global:CiProjectPath=$CI_PROJECT_DIR
  - $global:CommitId=$CI_BUILD_REF
  - $global:ProjectName=$CI_PROJECT_NAME
  - Import-Module -Name "$global:FilePath\\CI-Scripts.psm1"

## 构建模板
.job_build_template: &job_build_definition
  stage: build
  script: 
  - $JOB_NAME= -Split $CI_BUILD_NAME -replace "'",""
  - InvokeBuild -ProjectName:$JOB_NAME[1] -IsCore:($JOB_NAME[2] -eq 'IsCore')

## 构建主项目
Build '' IsCore:
  <<: *job_build_definition
  
## 构建测试项目
Build 'Ninetowns.IDecl.Tests' IsCore:
  <<: *job_build_definition
  artifacts: 
    name: "$CI_PROJECT_NAME/Test"
    expire_in: 1 day
    paths:
    - "BuildArtifacts"

## 测试模板
.job_test_template: &job_test_definition
  stage: test
  script:
  - $JOB_NAME= -Split $CI_BUILD_NAME -replace "'",""
  - Test -TestProjectName:$JOB_NAME[1] -IsCore:($JOB_NAME[2] -eq 'IsCore')
  coverage: '/"CoveragePercent": (\d+),/'
  variables:
    GIT_STRATEGY: none
  
## 测试项目
Test 'Ninetowns.IDecl.Tests' IsCore:
  <<: *job_test_definition
  dependencies:
  - Build 'Ninetowns.IDecl.Tests' IsCore

## 构建部署包
Build Unpack:
  stage: build_unpack
  script: 
  - BuildUnpack -ProjectName:'Ninetowns.IDecl.Web.Host' -IsCore
  artifacts: 
    name: "$CI_PROJECT_NAME"
    expire_in: 1 week
    paths:
    - "$CI_BUILD_REF.7z"
  only: 
  - pre-production
  - production

## 上传服务器模板
.job_upload_template: &job_upload_definition
  stage: upload_file
  script: 
  - $JOB_NAME= -Split $CI_BUILD_NAME
  - $ip=$JOB_NAME[1]
  - UploadFile "$ip"
  dependencies:
  - Build Unpack

## 上传到测试环境
Upload 192.168.3.80: 
  <<: *job_upload_definition
  only: 
  - pre-production


## 远程部署模板
.job_deploy_template: &job_deploy_definition
  stage: deploy
  script: 
  - $JOB_NAME= -Split $CI_BUILD_NAME
  - $ip=$JOB_NAME[1]
  - $site=$JOB_NAME[2]
  - DeployToRemote "$ip" "$site"
  variables:
    GIT_STRATEGY: none

## 部署测试环境
Deploy 192.168.3.80 WebiDecl: 
  <<: *job_deploy_definition
  environment:
    name: 192.168.3.80
  only: 
  - pre-production
  
## 本地部署模板
.job_deploy_template: &job_deploy_definition
  stage: deploy
  script: 
  - $JOB_NAME= -Split $CI_BUILD_NAME
  - $site=$JOB_NAME[1]
  - DeployToLocal -SiteName:"$site"
  variables:
    GIT_STRATEGY: none
    
## 本地部署测试环境
Deploy Test: 
  <<: *job_deploy_definition
  tags:
    - win
    - test
  environment:
    name: test
  only: 
  - test