## 
## Gitlab CI for .Net
##
## 作者:黄涛
## 站点:https://github.com/htve/GitlabCIForDotNet

## 构建的阶段与步骤
stages:
  - build
  - test
  - build_unpack
  - upload_file
  - deploy

## 定义变量
before_script:
  ##-----------------------------可变更参数----------------------------------
  ## 文件目录
  - $global:FilePath="C:\\Multi-Runner1"
  ## 进行单元测试及覆盖率的项目名称,多个文件用逗号(,)隔开,支持*通配符
  - $global:TestProjectNames="Ninetowns.NewsCenter.Tests"
  ## 覆盖率过滤器
  - $global:CoverFilters="-:Abp*"
  ##-------------------------------------------------------------------------
  - $global:CiProjectPath=$CI_PROJECT_DIR
  - $global:CommitId=$CI_BUILD_REF
  - $global:ProjectName=$CI_PROJECT_NAME
  - Import-Module -Name "$global:FilePath\\CI-Scripts.psm1"


## 构建主项目
Build Master Project:
  stage: build
  script:
  - InvokeBuildSln #非core
  #- InvokeBuildSln -IsCore #core
  
## 构建测试项目
Build Test Project:
  stage: build
  script:
  - InvokeMsBuildCsporj -TestProjectsName $global:TestProjectNames
  artifacts: 
    name: "$CI_PROJECT_NAME/Test"
    expire_in: 1 day
    paths:
    - "BuildTests"
    
## 测试项目
Test:
  stage: test
  variables:
    OUT_PATH: ""
    WEB_OUT_PATH: ""
  script:
  - Tests $global:TestProjectNames
  #- Tests $global:TestProjectNames -IsCore #Core 
  coverage: '/"CoveragePercent": (\d+),/'
  dependencies:
  - Build Test Project

## 构建部署包
Build Unpack:
  stage: build_unpack
  script: 
  - BuildUnpack
  artifacts: 
    name: "$CI_PROJECT_NAME"
    expire_in: 1 week
    paths:
    - "$CI_BUILD_REF.7z"
  only:
  - production

## 上传服务器模板
.job_upload_template: &job_upload_definition
  stage: upload_file
  script: 
  - $JOB_NAME= -Split $CI_BUILD_NAME
  - $ip=$JOB_NAME[1]
  - UploadFile "$ip"
  only: 
  - production
  dependencies:
  - Build Unpack

## 上传到192.168.3.80
Upload 192.168.3.80: *job_upload_definition

## 部署模板
.job_deploy_template: &job_deploy_definition
  stage: deploy
  script: 
  - $JOB_NAME= -Split $CI_BUILD_NAME
  - $ip=$JOB_NAME[1]
  - $site=$JOB_NAME[2]
  - Deploy "$ip" "$site"

## 部署192.168.3.80中的Site站点
Deploy 192.168.3.80 Site: 
  <<: *job_deploy_definition
  environment:
    name: 192.168.3.80
  only: 
  - production
  #如果想手动部署,请取消注释以下内容
  #when: manual